[package]
name = "tpex-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tpex = { path = "../tpex", version = "^0.1.0" }
axum = "^0.7.5"
tower-sessions = "^0.12.1"
tokio = { version = "^1.36.0", features = ["default", "rt-multi-thread"] }
clap = { version = "^4.5.4", features = ["derive"] }
serde_json = "^1.0.114"
